### ISSUE TITLE
YAML uncontrolled update in the dep chain causes error in CI

### ISSUE THREAD

**Issue by blaggacao** [pre-commit/pre-commit-hooks#1101]
### No pressure, this just happens sometimes (sic!) :smile: 

There seems to be an uncontrolled update in the dependency chain causing an incompatibility:

I'm reporting this within roughly the 1 hour window of the offending change as determined by a prior, still successful, CI run.

```
check yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo51rnf047/py_env-python3.10/bin/check-yaml", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repo51rnf047/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_yaml.py", line 64, in main
    load_fn(f)
  File "/home/runner/.cache/pre-commit/repo51rnf047/py_env-python3.10/lib/python3.10/site-packages/ruamel/yaml/main.py", line 451, in load
    return constructor.get_single_data()
  File "/home/runner/.cache/pre-commit/repo51rnf047/py_env-python3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 114, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 701, in ruamel.yaml.clib._ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 902, in ruamel.yaml.clib._ruamel_yaml.CParser._parse_next_event
  File "_ruamel_yaml.pyx", line 919, in ruamel.yaml.clib._ruamel_yaml.input_handler
TypeError: a string value is expected
Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo51rnf047/py_env-python3.10/bin/check-yaml", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repo51rnf047/py_env-python3.10/lib/python3.10/site-packages/pre_commit_hooks/check_yaml.py", line 64, in main
    load_fn(f)
  File "/home/runner/.cache/pre-commit/repo51rnf047/py_env-python3.10/lib/python3.10/site-packages/ruamel/yaml/main.py", line 451, in load
    return constructor.get_single_data()
  File "/home/runner/.cache/pre-commit/repo51rnf047/py_env-python3.10/lib/python3.10/site-packages/ruamel/yaml/constructor.py", line 114, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 701, in ruamel.yaml.clib._ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 902, in ruamel.yaml.clib._ruamel_yaml.CParser._parse_next_event
  File "_ruamel_yaml.pyx", line 919, in ruamel.yaml.clib._ruamel_yaml.input_handler
TypeError: a string value is expected
```

**Comment by PrivatePuffin** [comment]
Can confirm.

We should have this pinned btw:
https://github.com/pre-commit/pre-commit-hooks/blob/51c43c4b295db1ec59a56abc6afd06aa5fc862e0/setup.cfg#L22

**Comment by chintanms** [comment]
It would help if pinning versions on underling libraries for hooks is exposed to end users. 

Opened a placeholder issue on the underlying package repo: https://sourceforge.net/p/ruamel-yaml-clib/tickets/38/
I see a change made to the underling repo earlier today: https://github.com/ruamel/yaml.clib

**Comment by PrivatePuffin** [comment]
> It would help if pinning versions on underling libraries for hooks is exposed to end users.
> 
> Opened a placeholder issue on the underlying package repo: https://sourceforge.net/p/ruamel-yaml-clib/tickets/38/ I see a change made to the underling repo earlier today: https://github.com/ruamel/yaml.clib

Thats also a fair point indeed.

**Comment by PrivatePuffin** [comment]
@AvdN

**Comment by AvdN** [comment]
I yanked the offending release, I need to do more testing on all versions and platforms.

**Comment by asottile** [comment]
libraries should not pin.  you can always use `additional_dependencies` if you want to select a specific version

**Comment by PrivatePuffin** [comment]
> libraries should not pin. you can always use `additional_dependencies` if you want to select a specific version

The price for worse programming advice of the day goes to you, congrats!

**Comment by blaggacao** [comment]
> libraries should not pin.

Objection. But more kindly so. :smile:

Better not take this as advice!
