### ISSUE TITLE
requirements-txt-fixer broken for empty requirements.txt

### ISSUE THREAD

**Issue by asottile** [pre-commit/pre-commit-hooks#167]
A bit of an edge case, shouldn't crash though:

```python
Sorting requirements.txt
Traceback (most recent call last):
  File "/nail/tmp/tmp25dodv0q/venv/bin/requirements-txt-fixer", line 11, in <module>
    sys.exit(fix_requirements_txt())
  File "/nail/tmp/tmp25dodv0q/venv/lib/python3.5/site-packages/pre_commit_hooks/requirements_txt_fixer.py", line 84, in fix_requirements_txt
    ret_for_file = fix_requirements(file_obj)
  File "/nail/tmp/tmp25dodv0q/venv/lib/python3.5/site-packages/pre_commit_hooks/requirements_txt_fixer.py", line 64, in fix_requirements
    after_string = b''.join(after)
TypeError: sequence item 1: expected a bytes-like object, NoneType found
```

**Comment by bwbaugh** [comment]
Is there a use case for having an empty `requirements.txt`? I wouldn't be surprised if there were a few. Otherwise, maybe we could not crash but still return an error code? Having a requirements-checker hook when there are no requirements seems like a mistake.

**Comment by asottile** [comment]
I found this while attempting to satisfy the interface for the trivial case for upgrade-requirements on https://github.com/Yelp/requirements-tools (notably, an empty requirements-dev.txt)
