### ISSUE TITLE
Bug: IsADirectoryError for when adding submodules

### ISSUE THREAD

**Issue by shubhamchaudhary** [pre-commit/pre-commit-hooks#173]
### Affected hooks
This happens for following two hooks:
* detect-aws-credentials
* detect-private-key

### System information
Using the latest version of hooks and pre-commit.

### Steps to reproduce:
1. Have a repo with submodules.
1. Change submodules commit
1. Git Add submodule changes in root repo
1. Git commit (run hooks)

### Stacktrace
```
Detect AWS Credentials...................................................Failed
hookid: detect-aws-credentials

Traceback (most recent call last):
  File "/home/example/.pre-commit/repom8r_xu0y/py_env-default/bin/detect-aws-credentials", line 11, in <module>
    load_entry_point('pre-commit-hooks==0.7.1', 'console_scripts', 'detect-aws-credentials')()
  File "/home/example/.pre-commit/repom8r_xu0y/py_env-default/lib/python3.5/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 122, in main
    bad_filenames = check_file_for_aws_keys(args.filenames, keys)
  File "/home/example/.pre-commit/repom8r_xu0y/py_env-default/lib/python3.5/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 71, in check_file_for_aws_keys
    with open(filename, 'r') as content:
IsADirectoryError: [Errno 21] Is a directory: 'pyexample'

Detect Private Key.......................................................Failed
hookid: detect-private-key

Traceback (most recent call last):
  File "/home/example/.pre-commit/repom8r_xu0y/py_env-default/bin/detect-private-key", line 11, in <module>
    load_entry_point('pre-commit-hooks==0.7.1', 'console_scripts', 'detect-private-key')()
  File "/home/example/.pre-commit/repom8r_xu0y/py_env-default/lib/python3.5/site-packages/pre_commit_hooks/detect_private_key.py", line 22, in detect_private_key
    with open(filename, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: 'pyexample'
```

**Comment by asottile** [comment]
Thanks for the detailed report!

We're currently tracking this (wip) here: https://github.com/pre-commit/pre-commit/issues/191

As a workaround, it is suggested to add submodules / symlinks to the `exclude: ...` pattern though this will be addressed as a framework eventually.
