### ISSUE TITLE
pre-commit barfing on Mac

### ISSUE THREAD

**Issue by rayjohnson** [pre-commit/pre-commit-hooks#253]
I see this:
   
```
Traceback (most recent call last):
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/pre_commit/error_handler.py", line 47, in error_handler
    yield
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/pre_commit/main.py", line 240, in main
    skip_on_missing_conf=args.allow_missing_config,
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/pre_commit/commands/install_uninstall.py", line 85, in install
    install_hooks(runner)
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/pre_commit/commands/install_uninstall.py", line 92, in install_hooks
    repository.require_installed()
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/pre_commit/repository.py", line 202, in require_installed
    _install_all(self._venvs, self.repo_config['repo'], self.store)
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/pre_commit/repository.py", line 102, in _install_all
    language.install_environment(cmd_runner, version, deps)
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/pre_commit/languages/python.py", line 126, in install_environment
    repo_cmd_runner.run(venv_cmd, cwd='/', env=venv_env)
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/pre_commit/prefixed_command_runner.py", line 38, in run
    return cmd_output(*replaced_cmd, __popen=self.__popen, **kwargs)
  File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/pre_commit/util.py", line 187, in cmd_output
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/usr/local/Cellar/pre-commit/1.4.1/libexec/bin/python3.6', '-m', 'virtualenv', '/Users/rayj/.cache/pre-commit/repogm5nyids/py_env-default', '-p', '/usr/local/Cellar/pre-commit/1.4.1/libexec/bin/python3.6')
Return code: 1
Expected return code: 0
Output: 
    Already using interpreter /usr/local/Cellar/pre-commit/1.4.1/libexec/bin/python3.6
    Using real prefix '/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6'
    
Errors: 
    Traceback (most recent call last):
      File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 2328, in <module>
        main()
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 713, in main
        symlink=options.symlink)
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 925, in create_environment
        site_packages=site_packages, clear=clear, symlink=symlink))
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 1132, in install_python
        copy_required_modules(home_dir, symlink)
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 1063, in copy_required_modules
        copyfile(filename, dst_filename, symlink)
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/lib/python3.6/site-packages/virtualenv.py", line 343, in copyfile
        os.makedirs(os.path.dirname(dest))
      File "/usr/local/Cellar/pre-commit/1.4.1/libexec/bin/../lib/python3.6/os.py", line 220, in makedirs
        mkdir(name, mode)
    FileExistsError: [Errno 17] File exists: '/Users/rayj/.cache/pre-commit/repogm5nyids/py_env-default/lib/python3.6/lib-dynload'
```

**Comment by asottile** [comment]
Can you provide some additional information?  I've only seen a traceback like this when [running in applications which fail to correctly add `/usr/local/bin` to the `PATH`](https://github.com/pre-commit/pre-commit/issues/664#issuecomment-347681046)

Are you perhaps running from `SmartGit` / `SourceTree`?

**Comment by rayjohnson** [comment]
Not running SmartGit or SourceTree.

Installed pre-commit from from brew.  It did fail at some point for a reason I did not understand (and now do not have at my disposal.). However, when I did brew install pre-commit again it worked.

Other than that I'm not sure what additional information you would like.

**Comment by asottile** [comment]
Ok so it's working now?

If you hit this again, I'd like to see `echo "$PATH"` when you're running into it -- if it's the same way I was hitting it before that would be useful (I'm going to look at fixing this upstream in `virtualenv` as well, that's where the root-cause problem is from what I can tell).

Also if you find that other crash, I'm interested in a new report as well.  It's likely a framework-level problem and should be reported here: https://github.com/pre-commit/pre-commit/issues

Thanks again for the issue!

**Comment by rayjohnson** [comment]
No it is still broken.  Here is the path:
```

$ echo "$PATH"

/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/rayj/go/bin:/usr/local/opt/go/libexec/bin10084

```


The other crash was when installing from brew - that took a long time as
most of it appeared to be on dependencies like python.  Like I said I just
ran brew install pre-commit again and it worked the second time.  But it
could be one of the dependencies are not happy.  Unfortunately, I no longer
have a record of that interaction.

**Comment by asottile** [comment]
Ah ok.  Now to try and figure out why it's broken!

Can you provide the outputs of `brew list`, `which python3`, `which python3.6`?

**Comment by rayjohnson** [comment]
```
$ brew list 
aspell		dep		freetype	hugo		openssl		sqlite
awscli		docker-machine	gd		jpeg		pkg-config	webp
bash-completion	dry		gdbm		libpng		pre-commit	xz
bazaar		dvm		go		libtiff		python3
ctop		fontconfig	graphviz	libtool		readline
```

which python3 and which python3.6 returned nothing!

So - I did this:
```
$ brew install python3
Warning: python3 3.6.3 is already installed, it's just not linked.
You can use `brew link python3` to link this version.
```

and this

```
$ brew link python3
Linking /usr/local/Cellar/python3/3.6.3... Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks
```

Trying to fix it I did this:
```
$ sudo mkdir /usr/local/Frameworks
$ sudo chown rayj /usr/local/Frameworks/
$ sudo chgrp admin /usr/local/Frameworks/

$ brew link python3
Linking /usr/local/Cellar/python3/3.6.3... 1 symlinks created
```

NOW pre-commit install --install-hooks appears to work.  I'll try it out!

Thank you!  (And I hope the additional info helps you!)

**Comment by asottile** [comment]
fwiw, I believe this to be a `brew` issue, I've created an issue with some detailed analysis here: https://github.com/Homebrew/homebrew-core/issues/21386

**Comment by asottile** [comment]
btw, we got the root cause fixed in homebrew 🎉

**Comment by rayjohnson** [comment]
Awesome!
