### ISSUE TITLE
AttributeError in check-builtin-literals hook.

### ISSUE THREAD

**Issue by EgoWumpus** [pre-commit/pre-commit-hooks#285]
The `check-builtin-literals` hook is consistently failing for me, but I don't know why. This is the error I'm getting:

```
Check builtin type constructor use.......................................Failed
hookid: check-builtin-literals

Traceback (most recent call last):
  File "/Users/nmford/.cache/pre-commit/repoco9z7yr8/py_env-python3.6/bin/check-builtin-literals", line 11, in <module>
    sys.exit(main())
  File "/Users/nmford/.cache/pre-commit/repoco9z7yr8/py_env-python3.6/lib/python3.6/site-packages/pre_commit_hooks/check_builtin_literals.py", line 79, in main
    allow_dict_kwargs=args.allow_dict_kwargs,
  File "/Users/nmford/.cache/pre-commit/repoco9z7yr8/py_env-python3.6/lib/python3.6/site-packages/pre_commit_hooks/check_builtin_literals.py", line 52, in check_file_for_builtin_type_constructors
    visitor.visit(tree)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/nmford/.cache/pre-commit/repoco9z7yr8/py_env-python3.6/lib/python3.6/site-packages/pre_commit_hooks/check_builtin_literals.py", line 38, in visit_Call
    if node.func.id not in set(BUILTIN_TYPES).difference(self.ignore):
AttributeError: 'Call' object has no attribute 'id'
```

This is how the config yaml is configured:
```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 805530fe2934a55dc399f80615725157dec5f062
    hooks:
    -   id: check-ast
    -   id: check-builtin-literals  # Seems to have an issue in the library
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: flake8
        args: [--max-line-length=120]
        exclude: '(smoke_)?specs\/'
    -   id: mixed-line-ending
    -   id: name-tests-test
        args: [--django]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
```

**Comment by asottile** [comment]
ah yeah this makes sense, probably not guarding that the call is actually a function -- should be an easy patch let me try and fix it :D

**Comment by asottile** [comment]
Here's a minimal case which causes it to crash:

```python
x[]()
```

**Comment by EgoWumpus** [comment]
If you don't have time for a patch, let me know and I can try and put one together. I am happy to be validated that it's a real bug. :)

**Comment by asottile** [comment]
Already fixed! would definitely appreciate a review if you have the time right now :D https://github.com/pre-commit/pre-commit-hooks/pull/286

**Comment by EgoWumpus** [comment]
Thanks for the super quick fix!!!

**Comment by asottile** [comment]
This has been (finally!) released as part of [v1.3.0](https://github.com/pre-commit/pre-commit-hooks/releases/tag/v1.3.0)! 🎉
