### ISSUE TITLE
Hooks failing with DistributionNotFound

### ISSUE THREAD

**Issue by hectorv** [pre-commit/pre-commit-hooks#328]
In one of our repos we're using `pre-commit 1.3.0` and some hooks from this repo started failing with
```
pkg_resources.DistributionNotFound: The 'pycodestyle>=2.4.0' distribution was not found and is required by autopep8
```
here's a snippet with the traceback: 
```
Trim Trailing Whitespace.................................................Failed
hookid: trailing-whitespace

Traceback (most recent call last):
  File "/root/.cache/pre-commit/repoqYVsQ8/py_env-python2.7/bin/trailing-whitespace-fixer", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/root/.cache/pre-commit/repoqYVsQ8/py_env-python2.7/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/root/.cache/pre-commit/repoqYVsQ8/py_env-python2.7/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/root/.cache/pre-commit/repoqYVsQ8/py_env-python2.7/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/root/.cache/pre-commit/repoqYVsQ8/py_env-python2.7/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/root/.cache/pre-commit/repoqYVsQ8/py_env-python2.7/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/root/.cache/pre-commit/repoqYVsQ8/py_env-python2.7/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycodestyle>=2.4.0' distribution was not found and is required by autopep8
```
Happy to provide any more information to narrow this down.
Thanks!

**Comment by asottile** [comment]
This has been fixed in 2.0.0 :tada:
