### ISSUE TITLE
UnicodeDecodeError in detect-aws-credentials is unreadable

### ISSUE THREAD

**Issue by rpdelaney** [pre-commit/pre-commit-hooks#346]
```
Detect AWS Credentials...................................................Failed
hookid: detect-aws-credentials

Traceback (most recent call last):
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/bin/detect-aws-credentials", line 11, in <module>
    sys.exit(main())
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 133, in main
    bad_filenames = check_file_for_aws_keys(args.filenames, keys)
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 74, in check_file_for_aws_keys
    text_body = content.read()
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 103: invalid continuation byte
Traceback (most recent call last):
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/bin/detect-aws-credentials", line 11, in <module>
    sys.exit(main())
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 133, in main
    bad_filenames = check_file_for_aws_keys(args.filenames, keys)
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 74, in check_file_for_aws_keys
    text_body = content.read()
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 2346: invalid start byte
Traceback (most recent call last):
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/bin/detect-aws-credentials", line 11, in <module>
    sys.exit(main())
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 133, in main
    bad_filenames = check_file_for_aws_keys(args.filenames, keys)
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 74, in check_file_for_aws_keys
    text_body = content.read()
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 187: invalid continuation byte
Traceback (most recent call last):
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/bin/detect-aws-credentials", line 11, in <module>
    sys.exit(main())
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 133, in main
    bad_filenames = check_file_for_aws_keys(args.filenames, keys)
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/site-packages/pre_commit_hooks/detect_aws_credentials.py", line 74, in check_file_for_aws_keys
    text_body = content.read()
  File "/home/ryan/.cache/pre-commit/repo8jj7q4iz/py_env-python3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 167: invalid continuation byte
```

It rejected the commit, so that's good. And I'm not sure if I can recommend any improvements to the handling of invalid unicode since I haven't looked at the code in this module.

But for sure this error message could be more useful. There are 773 files in this commit and it would sure be nice to know which one(s) have this problem.

Edit: Ideally if there's an exception it would continue to the next file so all the files that couldn't be processed can be listed to the user before the commit is rejected. I'm not looking forward to fixing one file, doing `git commit`, fixing another... 500 times. ;)

**Comment by asottile** [comment]
agreed, this can be improved.  

Looks like there's some prior art [here](https://github.com/pre-commit/pre-commit-hooks/blob/63e729fcc7d7fa21db65e1a62f1e53140f594aaf/pre_commit_hooks/check_json.py#L18-L20) or in [pyupgrade](https://github.com/asottile/pyupgrade/blob/fe5063ffea0c30f6425b15421eb384939eab3a01/pyupgrade.py#L1317-L1321) if you'd like to apply it to this (and others here!)

**Comment by acdha** [comment]
This also breaks `pre-commit run --all-files` — I was trying to test updated config and got that stack trace when it hit an image file.

**Comment by asottile** [comment]
What was your configuration? by default this hook only runs on files which are identified as `[text]`

**Comment by acdha** [comment]
I had just added this block:

```yaml
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
          - id: check-byte-order-marker
          - id: trailing-whitespace
          - id: check-merge-conflict
          - id: flake8
          - id: check-json
          - id: detect-aws-credentials
```

I wanted to confirm that my new rules weren't going to fail any existing files in the repo so I started `pre-commit run --all-files` while I was working on the commit message and got that `UnicodeDecodeError`.

**Comment by asottile** [comment]
Is this in an open source repository I can look at?

**Comment by acdha** [comment]
It is now: https://github.com/LibraryOfCongress/concordia/pull/774

**Comment by acdha** [comment]
I should note that it works fine in normal usage since the text filter is there. It's only in the `--all-files` case that it blows up.

**Comment by asottile** [comment]
it seems that `.plist` is being identified as a text file:
```
$ ~/opt/venv/bin/identify-cli cloudformation/images/architecture-overview.graffle/data.plist
["file", "non-executable", "plist", "text"]
```

due to this: https://github.com/chriskuehl/identify/blob/1af88acc98ca80bf0c716241e35544d18337540f/identify/extensions.py#L100

hmm now to figure out if it's that plist is not text or whether that file has an incorrect extension 🤔

**Comment by asottile** [comment]
Looks like the extension can be binary or text :/

identify will probably need to grow some logic to handle that

**Comment by acdha** [comment]
Yech — when I ran it under pdb, it hit `favicon.ico`, too. Let me see if I can reproduce it.

**Comment by acdha** [comment]
In this case I'm not sure that file needs to be in this repo but obviously that's not a great general answer.

**Comment by asottile** [comment]
I'm working on a fix for `identify` -- it needs to dynamically check binary / text for `.plist` files since apple's standard is nutso

**Comment by acdha** [comment]
As a long-time Mac sysadmin, rest assured that I feel your pain on that. Their tools left a LOT to be desired for anyone outside of the Objective C world.

**Comment by asottile** [comment]
After fixing plist detection (via `identify>=1.2.0`) that passes now 🎉 

```
$ pre-commit run detect-aws-credentials --all-files
Detect AWS Credentials...................................................Passed
$ 
```

**Comment by leberknecht** [comment]
I also ran into this, but on a text-file. Changing 
```
with open(filename, 'r') as content:
```
to 
```
with open(filename, 'r', encoding='utf-8') as content:
```
in `pre_commit_hooks/detect_aws_credentials.py:74` solved it for me. Dunno, is it just me / my system?

**Comment by asottile** [comment]
Do you have a reproduction? what platform are you on? do you want to submit a patch?

**Comment by maximveksler** [comment]
I see pre-commit failing on the following error for one of the files in our code base


```
User@DESKTOP-S63ANC6 MINGW64 ~/code/SEED (supercharge_precommit)
$ pre-commit run --all-files
black....................................................................Passed
Check for added large files..............................................Passed
Check for byte-order marker..............................................Passed
Check for case conflicts.................................................Passed
Check python ast.........................................................Passed
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect AWS Credentials...................................................Failed
hookid: detect-aws-credentials

trainx/blocks/create_scatter.py
~~~~150 lines reducted~~~~
trainx_2/blocks/example_gen/example_gen/csv_result.py
Traceback (most recent call last):
  File "c:\python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\.cache\pre-commit\repoit6w26lg\py_env-python3.7\Scripts\detect-aws-credentials.exe\__main__.py", line 9, in <module>
  File "c:\users\user\.cache\pre-commit\repoit6w26lg\py_env-python3.7\lib\site-packages\pre_commit_hooks\detect_aws_credentials.py", line 140, in main
    bad_filenames = check_file_for_aws_keys(args.filenames, keys)
  File "c:\users\user\.cache\pre-commit\repoit6w26lg\py_env-python3.7\lib\site-packages\pre_commit_hooks\detect_aws_credentials.py", line 81, in check_file_for_aws_keys
    text_body = content.read()
  File "c:\users\user\.cache\pre-commit\repoit6w26lg\py_env-python3.7\lib\encodings\cp1255.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9c in position 204: character maps to <undefined>

Detect Private Key.......................................................Passed
Forbid new submodules....................................................Passed
Pretty format JSON.......................................................Passed
Fix requirements.txt.....................................................Passed
Trim Trailing Whitespace.................................................Passed
```

I've added some prints and found the problematic file (attached as zip to preserve encoding)

[csv_result.zip](https://github.com/pre-commit/pre-commit-hooks/files/4218850/csv_result.zip)

**Comment by asottile** [comment]
#393 (in progress) is aiming to fix this

**Comment by asottile** [comment]
I decided to pick this up in #453
