### ISSUE TITLE
Check Yaml has occurred an error on Windows by open() function

### ISSUE THREAD

**Issue by roottool** [pre-commit/pre-commit-hooks#377]
## Description
`Check Yaml` has occurred an error like the below when I executed `pre-commit run --all-files` on Windows.

```text
Check Yaml...............................................................Failed
hookid: check-yaml

Traceback (most recent call last):
  File "c:\python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\smart\.cache\pre-commit\repoh33xm34r\py_env-python3.7\Scripts\check-yaml.exe\__main__.py", line 9, in <module>
  File "c:\users\smart\.cache\pre-commit\repoh33xm34r\py_env-python3.7\lib\site-packages\pre_commit_hooks\check_yaml.py", line 60, in check_yaml
    load_fn(open(filename), Loader=Loader)
  File "c:\users\smart\.cache\pre-commit\repoh33xm34r\py_env-python3.7\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "c:\users\smart\.cache\pre-commit\repoh33xm34r\py_env-python3.7\lib\site-packages\yaml\constructor.py", line 41, in get_single_data
    node = self.get_single_node()
  File "ext\_yaml.pyx", line 702, in _yaml.CParser.get_single_node
  File "ext\_yaml.pyx", line 903, in _yaml.CParser._parse_next_event
  File "ext\_yaml.pyx", line 912, in _yaml.input_handler
UnicodeDecodeError: 'cp932' codec can't decode byte 0x84 in position 1018: illegal multibyte sequence
```

This reason is that `encoding='UTF-8` does not exist in `open()` function.
https://github.com/pre-commit/pre-commit-hooks/blob/e6e26c3110d1acd50544957a3bbaac4f89057a25/pre_commit_hooks/check_yaml.py#L61

## Suggestion

I suggest that we should add `encoding='UTF-8'` like the below.
https://github.com/pre-commit/pre-commit-hooks/blob/e6e26c3110d1acd50544957a3bbaac4f89057a25/pre_commit_hooks/check_json.py#L19

**Comment by asottile** [comment]
Sounds good, would you like to contribute the PR for that? You'll want to switch to `io.open` there

**Comment by roottool** [comment]
OK, I try it.
