### ISSUE TITLE
Yaml Merge Keys give false positive

### ISSUE THREAD

**Issue by ericfrederich** [pre-commit/pre-commit-hooks#468]
The check-yaml is giving an error for the following valid YAML file.  It is identifying `<<` as a key

It seems [Merge Key](https://yaml.org/type/merge.html)s are not supported by ruamel.yaml.  Perhaps stop using this yaml package.  I tried to find the source for it.  From PyPI it links to BitBucket where it has been deleted and links to SourceForge which of littered with advertisments.  Also SourceForge has a history of embedding malware.

### example.yml

```yaml
.foo: &foo
  spam:
    - one
    - two

.bar: &bar
  eggs:
    - three
    - four

example:
  <<: *foo
  <<: *bar
```

### The error

```
Traceback (most recent call last):
  File "/home/eric/.cache/pre-commit/repofg6bh5oq/py_env-python3.8/bin/check-yaml", line 8, in <module>
    sys.exit(main())
  File "/home/eric/.cache/pre-commit/repofg6bh5oq/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/check_yaml.py", line 63, in main
    load_fn(f)
  File "/home/eric/.cache/pre-commit/repofg6bh5oq/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/main.py", line 343, in load
    return constructor.get_single_data()
  File "/home/eric/.cache/pre-commit/repofg6bh5oq/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
  File "/home/eric/.cache/pre-commit/repofg6bh5oq/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 123, in construct_document
    for _dummy in generator:
  File "/home/eric/.cache/pre-commit/repofg6bh5oq/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 723, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/eric/.cache/pre-commit/repofg6bh5oq/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 439, in construct_mapping
    self.flatten_mapping(node)
  File "/home/eric/.cache/pre-commit/repofg6bh5oq/py_env-python3.8/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 396, in flatten_mapping
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "example.yml", line 12, column 3
found duplicate key "<<"
  in "example.yml", line 13, column 3
```

**Comment by asottile** [comment]
please report to `ruamel.yaml`, thanks!

**Comment by asottile** [comment]
actually, from reading [this](https://stackoverflow.com/a/52852106/812183) it looks like that yaml is indeed invalid and it should be:

```yaml
  <<: [*foo, *bar]
```

and likely whatever parser you're using to load this separately is not adhering to the spec
