### ISSUE TITLE
These hooks do not work with Python3.8

### ISSUE THREAD

**Issue by rambo** [pre-commit/pre-commit-hooks#470]
Because they ask for exactly 3.7 instead of 3.7 or newer.

This makes life a bit complicated when working on python3.8 projects (having to install separate 3.7 on the side just to run the hooks).

**Comment by rambo** [comment]
Here's the error and log

```
docker:/app# pre-commit run --all-files
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-pylint.
[INFO] Initializing environment for https://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/PyCQA/bandit.
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks-markup.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3.8', '-mvirtualenv', '/root/.cache/pre-commit/reposvdgj9kt/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)
Check the log at /root/.cache/pre-commit/pre-commit.log


docker:/app# cat /root/.cache/pre-commit/pre-commit.log
### version information

pre-commit version: 1.21.0
sys.version:
    3.8.2 (default, Feb 29 2020, 17:03:31) 
    [GCC 9.2.0]
sys.executable: /usr/bin/python3.8
os.name: posix
sys.platform: linux

### error information

An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/python3.8', '-mvirtualenv', '/root/.cache/pre-commit/reposvdgj9kt/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pre_commit/error_handler.py", line 72, in error_handler
    yield
  File "/usr/lib/python3.8/site-packages/pre_commit/main.py", line 344, in main
    return run(args.config, store, args)
  File "/usr/lib/python3.8/site-packages/pre_commit/commands/run.py", line 292, in run
    install_hook_envs(hooks, store)
  File "/usr/lib/python3.8/site-packages/pre_commit/repository.py", line 220, in install_hook_envs
    hook.install()
  File "/usr/lib/python3.8/site-packages/pre_commit/repository.py", line 97, in install
    lang.install_environment(
  File "/usr/lib/python3.8/site-packages/pre_commit/languages/python.py", line 169, in install_environment
    _make_venv(env_dir, python)
  File "/usr/lib/python3.8/site-packages/pre_commit/languages/python.py", line 181, in make_venv
    cmd_output_b(*cmd, env=env, cwd='/')
  File "/usr/lib/python3.8/site-packages/pre_commit/util.py", line 141, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/python3.8', '-mvirtualenv', '/root/.cache/pre-commit/reposvdgj9kt/py_env-python3.7', '-p', 'python3.7')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
    
stderr: (none)

```

**Comment by asottile** [comment]
show your configuration?

**Comment by rambo** [comment]
```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.7
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: no-commit-to-branch
    -   id: check-executables-have-shebangs
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: pretty-format-json
        args:
        - --autofix
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.7
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.760
    hooks:
    -   id: mypy
        language: system
        args: [--strict] #, --ignore-missing-imports]
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.4.4
    hooks:
    -   id: pylint
        language: system
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    - id: bandit
      args: ["--skip=B101"]
-   repo: git://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.0
    hooks:
    -   id: rst-linter
````

I think I see the problem now... funny how I missed that...

**Comment by asottile** [comment]
PEBKAC ;)

this repository does not specify a python version so it has to be your configuration
