### ISSUE TITLE
error loading a removed hook

### ISSUE THREAD

**Issue by pedrocalleja** [pre-commit/pre-commit-hooks#485]
when load a removed hook throw this error

```
Flake8 (removed).........................................................Failed
- hook id: flake8
- exit code: 1

Traceback (most recent call last):
  File "/Users/pedro/.cache/pre-commit/repo3ku28fr9/py_env-python3.8/bin/pre-commit-hooks-removed", line 8, in <module>
    sys.exit(main())
  File "/Users/pedro/.cache/pre-commit/repo3ku28fr9/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/removed.py", line 8, in main
    hookid, new_hookid, url = argv
ValueError: too many values to unpack (expected 3)
```

**Comment by asottile** [comment]
can you share your config?

**Comment by pedrocalleja** [comment]
better !!! I have a PR ready to fix that

**Comment by pedrocalleja** [comment]
I user define extra argument for a removed hook this bug came out. the simple solution is get only the first three arguments to raise the removed hook message
