### ISSUE TITLE
pretty-format-json exception on UTF-16 files

### ISSUE THREAD

**Issue by jdrowne** [pre-commit/pre-commit-hooks#541]
We have some files encoded in UTF-16 because they are used by Windows systems. If you use `pre-commit run pretty-format-json --all-files` in the repo's root directory, the hook throws an Exception:

```Traceback (most recent call last):
  File "/Users/jdrowne/.cache/pre-commit/repoyjdtd_1v/py_env-python3.9/bin/pretty-format-json", line 8, in <module>
    sys.exit(main())
  File "/Users/jdrowne/.cache/pre-commit/repoyjdtd_1v/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/pretty_format_json.py", line 114, in main
    contents = f.read()
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte```

**Comment by asottile** [comment]
json must be utf-8, utf-16 encoded json is not valid according to spec

the tool is correct to raise an error on poorly encoded files
