### ISSUE TITLE
destroyed-symlinks fails on travis-ci.com because git is too old

### ISSUE THREAD

**Issue by ylep** [pre-commit/pre-commit-hooks#628]
When `git` is too old, such as in the Ubuntu xenial-based images on [travis-ci.com](https://travis-ci.com/), the `destroyed-symlinks` hook fails because `git` fails with `error: option 'porcelain' takes no value` (full traceback below).

If the newer Git is really needed, maybe this hook should be skipped in that case, and/or the limitation documented?

```
Traceback (most recent call last):
  File "/home/travis/.cache/pre-commit/repozjoh7t0y/py_env-python3.8/bin/destroyed-symlinks", line 8, in <module>
    sys.exit(main())
  File "/home/travis/.cache/pre-commit/repozjoh7t0y/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/destroyed_symlinks.py", line 73, in main
    destroyed_links = find_destroyed_symlinks(files=args.filenames)
  File "/home/travis/.cache/pre-commit/repozjoh7t0y/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/destroyed_symlinks.py", line 21, in find_destroyed_symlinks
    cmd_output('git', 'status', '--porcelain=v2', '-z', '--', *files),
  File "/home/travis/.cache/pre-commit/repozjoh7t0y/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/util.py", line 24, in cmd_output
    raise CalledProcessError(cmd, retcode, proc.returncode, stdout, stderr)
pre_commit_hooks.util.CalledProcessError: (('git', 'status', '--porcelain=v2', '-z', '--', 'share/distro/bvdev/casa_distro.json', 'share/docker/casa-run/ubuntu-18.04/build_sip_pyqt.sh', 'tox.ini', 'share/distro/cati_platform/casa_distro.json'), 0, 129, '', b"error: option `porcelain' takes no value\nusage: git status [<options>] [--] <pathspec>...\n\n    -v, --verbose         be verbose\n    -s, --short           show status concisely\n    -b, --branch          show branch information\n    --porcelain           machine-readable output\n    --long                show status in long format (default)\n    -z, --null            terminate entries with NUL\n    -u, --untracked-files[=<mode>]\n                          show untracked files, optional modes: all, normal, no. (Default: all)\n    --ignored             show ignored files\n    --ignore-submodules[=<when>]\n                          ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)\n    --column[=<style>]    list untracked files in columns\n\n")
```

**Comment by asottile** [comment]
actually I think crashing is the safest thing to do here -- wouldn't want to silently allow failure
