### ISSUE TITLE
detect-private-key hook appears to crash with images in the directory

### ISSUE THREAD

**Issue by Xelblade** [pre-commit/pre-commit-hooks#64]
Just added some images and a resources.qrc file to my PyQt4 project and got this error out of it. Is it because it tries to decode images as text?

```
Detect Private Key.......................................................Failed
hookid: detect-private-key

Traceback (most recent call last):

  File "C:\cygwin64\home\builder\.pre-commit\repo7jrxo4\py_env-default\Scripts\detect-private-key-script.py", line 9, in \<module\>

    load_entry_point('pre-commit-hooks==0.4.2', 'console_scripts', 'detect-private-key')()

  File "C:\cygwin64\home\builder\.pre-commit\repo7jrxo4\py_env-default\lib\site-packages\pre_commit_hooks\detect_private_key.py", line 17, in detect_private_key

    content = f.read()

  File "C:\cygwin64\home\builder\.pre-commit\repo7jrxo4\py_env-default\lib\encodings\cp1252.py", line 23, in decode

    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 44: character maps to \<undefined\>
```

**Comment by asottile** [comment]
ohp, this hook needs to read files as binary (which should be fine since rsa is ascii anyways).  This should be a pretty straightforward fix -- I'll take a look at this tomorrow

**Comment by asottile** [comment]
@Xelblade this should be fixed now.  Thanks for the report! :+1:
