### ISSUE TITLE
check-merge-conflict doesn't catch conflict markers

### ISSUE THREAD

**Issue by kubijo** [pre-commit/pre-commit-hooks#660]
## `.pre-commit-config.yaml`

```yaml
# See https://pre-commit.com for more information
fail_fast: false
repos: [
  {
    repo: "https://github.com/pre-commit/pre-commit-hooks",
    rev: "v4.0.1",
    hooks: [
      # GIT
      { id: "check-merge-conflict" },
      { id: "check-added-large-files" },

      # Sys
      { id: "check-case-conflict" },
      { id: "check-executables-have-shebangs" },
      { id: "check-shebang-scripts-are-executable" },

      # FS
      { id: "check-symlinks" },
      { id: "destroyed-symlinks" },

      # Syntax
      #{ id: "check-yaml" },
      { id: "end-of-file-fixer" },
    ],
  },
]
```

## Example code used for testing

```rust
// Dummy comment not to trip shebang detection
#![cfg_attr(
  all(not(debug_assertions), target_os = "windows"),
  windows_subsystem = "windows"
)]

fn main() {
  tauri::Builder::default()
    .run(tauri::generate_context!())
    .expect("BUG: error while running tauri application");
}

If you have questions, please
<<<<<<< HEAD
open an issue
=======
ask your question in IRC.
>>>>>>> branch-a
```

```package.json
{
    "version": "1.0.0",
    "devDependencies": {
<<<<<<< HEAD
this is some content to mess with
content to append
=======
totally different content to merge later
>>>>>>> new_branch_to_merge_later
        "type-fest": "2.3.2",
        "typescript": "4.4.2"
    }
}
```

## CLI ouput for `pre-commit run --all-files --show-diff-on-failure --verbose`
```bash
Check for merge conflicts................................................Passed
Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check that executables have shebangs.................(no files to check)Skipped
Check that scripts with shebangs are executable..........................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Destroyed Symlinks................................................Passed
Fix End of Files.........................................................Passed
Format python........................................(no files to check)Skipped
Format JavaScript........................................................Failed
- hook id: format-js
- exit code: 1

Syntax Error: Unexpected token < in JSON at position 1241 (when parsing /opt/dev/braiins/pool/web-ui/packages/toolbox/package.json)
    at JSON.parse (<anonymous>)
    at la.loadFile (/opt/dev/braiins/pool/web-ui/.yarn/releases/yarn-3.1.0-rc.2.cjs:271:4655)
    at async Function.fromFile (/opt/dev/braiins/pool/web-ui/.yarn/releases/yarn-3.1.0-rc.2.cjs:271:4165)
    at async Function.tryFind (/opt/dev/braiins/pool/web-ui/.yarn/releases/yarn-3.1.0-rc.2.cjs:271:3931)
    at async Function.find (/opt/dev/braiins/pool/web-ui/.yarn/releases/yarn-3.1.0-rc.2.cjs:271:4009)
    at async Kf.setup (/opt/dev/braiins/pool/web-ui/.yarn/releases/yarn-3.1.0-rc.2.cjs:300:5445)
    at async Ne.addWorkspace (/opt/dev/braiins/pool/web-ui/.yarn/releases/yarn-3.1.0-rc.2.cjs:304:2080)
    at async Ne.setupWorkspaces (/opt/dev/braiins/pool/web-ui/.yarn/releases/yarn-3.1.0-rc.2.cjs:304:1866)
    at async Function.find (/opt/dev/braiins/pool/web-ui/.yarn/releases/yarn-3.1.0-rc.2.cjs:301:1406)
    at async jp.execute (/opt/dev/braiins/pool/web-ui/.yarn/releases/yarn-3.1.0-rc.2.cjs:424:1845)
```

**Comment by asottile** [comment]
there's a precondition that you're either in a merge conflict *or* you've set the unsafe `--assume-in-merge` option: https://github.com/pre-commit/pre-commit-hooks/blob/e35ba8d463d783ad7d8189213b5426c0a2c9de3b/pre_commit_hooks/check_merge_conflict.py#L32
