### ISSUE TITLE
New ruamel.yaml library creates a regression on check_yaml hook

### ISSUE THREAD

**Issue by ljmf00** [pre-commit/pre-commit-hooks#710]
Given the YAML files generated by [dstask](https://github.com/naggie/dstask) to `check_yaml` pre-commit hook using `ruamel.yaml`, the following backtrace is generated:

<details>
<summary>Details</summary>

```
Traceback (most recent call last):
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/bin/check-yaml", line 8, in <module>
    sys.exit(main())
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/pre_commit_hooks/check_yaml.py", line 63, in main
    load_fn(f)
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/main.py", line 434, in load
    return constructor.get_single_data()
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 121, in get_single_data
    return self.construct_document(node)
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 131, in construct_document
    for _dummy in generator:
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 674, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 445, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 261, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 154, in construct_object
    data = self.construct_non_recursive_object(node)
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 189, in construct_non_recursive_object
    data = constructor(self, node)
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 573, in construct_yaml_timestamp
    return create_timestamp(**values)
  File "/pc/clone/lfqkO38kRCeSJaDqZ374rg/py_env-python3/lib/python3.8/site-packages/ruamel/yaml/util.py", line 104, in create_timestamp
    data = datetime.datetime(year, month, day, hour, minute, second, fraction)
ValueError: microsecond must be in 0..999999
```

</details>

I have tested the generated YAMLs using `v2.2.0` of the hooks and seem to be validating them correctly. I have a collection of YAML files generated by this tool in [this](https://github.com/ljmf00/tasks) repo. An example of generated YAML file:

```yaml
summary: DW_AT_decl_line should report 32bit on the DWARF info
notes: ""
tags:
- dmd
project: saoc2021
priority: P2
delegatedto: ""
subtasks: []
dependencies: []
created: 2021-10-21T20:10:39.485461687+01:00
resolved: 2021-11-08T02:05:29.104026669Z
due: 0001-01-01T00:00:00Z
```

See https://results.pre-commit.ci/run/github/415737065/1641176469.F7pxlaBURQKu9RNChDZz7w for detailed error on pre-commit.ci

**Comment by asottile** [comment]
I have no control over ruamel.yaml -- please report it to them

**Comment by ljmf00** [comment]
> I have no control over ruamel.yaml -- please report it to them

Cross-referencing the upstream ticket: https://sourceforge.net/p/ruamel-yaml/tickets/414/

**Comment by asottile** [comment]
by the way your yaml in this issue doesn't reproduce the problem -- so you might want to find the actual yaml which does and report it there
