### ISSUE TITLE
v4.1.0 breaks check-added-large-files

### ISSUE THREAD

**Issue by jfcrenshaw** [pre-commit/pre-commit-hooks#718]
After setting `rev: v4.1.0` in `.pre-commit-config.yaml`, `check-added-large-files` fails with the following error:

```
check for added large files..............................................Failed
- hook id: check-added-large-files
- exit code: 1

Traceback (most recent call last):
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
Traceback (most recent call last):
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/phys/users/jfc20/.cache/pre-commit/repocp57goij/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
```

Everything runs fine when I set `rev: v4.0.1`.

**Comment by asottile** [comment]
cc @amartani #674

@jfcrenshaw please provide more information, notably what git version you're using

**Comment by jfcrenshaw** [comment]
git version 1.8.3.1
pre-commit 2.16.0
Python 3.9.9
CentOS Linux 7 (Core)

**Comment by asottile** [comment]
yeah 10 year old git is probably the problem -- I'd recommend you upgrade that

**Comment by asottile** [comment]
this was a bug in git fixed in1.8.5 in 2013

**Comment by vanaoff** [comment]
This may help someone... We had in `.gitattributes` something like
```
README.* filter= diff= merge= text
```
That caused that attributes for `README.*` files was empty string in `git check-attr filter -z`. So if the `check-added-large-files` got some `README.*` file as the last (files are in set, so they're processed in random order), function `pre_commit.git.zsplit` stripped all trailing null characters which caused this pre-commit hook to fail for exactly this reason.
