### ISSUE TITLE
IndexError at check-added-large-files hook

### ISSUE THREAD

**Issue by chuber1986** [pre-commit/pre-commit-hooks#729]
After upgrading pre-commit-hooks  to v4.1.0 i get an IndexError when the check-added-large-files hook is executed.

```
check for added large files..............................................Failed
- hook id: check-added-large-files
- exit code: 1

Traceback (most recent call last):
  File "/home/<user>/.cache/pre-commit/repotjg_t3um/py_env-python3.8/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/<user>/.cache/pre-commit/repotjg_t3um/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/check_added_large_files.py", line 73, in main
    return find_large_added_files(
  File "/home/<user>/.cache/pre-commit/repotjg_t3um/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/check_added_large_files.py", line 43, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/<user>/.cache/pre-commit/repotjg_t3um/py_env-python3.8/lib/python3.8/site-packages/pre_commit_hooks/check_added_large_files.py", line 28, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
```

No arguments passed. My `.pre-commit-config.yaml`:
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: check-added-large-files
      - id: fix-encoding-pragma
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: detect-private-key
```

**Comment by asottile** [comment]
search the issue tracker next time

**Comment by chuber1986** [comment]
sorry, must have had a typo in my search query
