### ISSUE TITLE
debug-statements hook not working with Python3.10 pattern matching syntax

### ISSUE THREAD

**Issue by flaiming** [pre-commit/pre-commit-hooks#733]
Hi, I'm unable to run `debug-statements` hook because it is giving me syntax error on Python 3.10 pattern matching syntax.
```
Debug Statements (Python)................................................Failed
- hook id: debug-statements
- exit code: 1

apps/outreach/management/commands/outreach_job.py - Could not parse ast

	Traceback (most recent call last):
	  File "/home/flaim/.cache/pre-commit/repopaa8460j/py_env-python3.9/lib/python3.9/site-packages/pre_commit_hooks/debug_statement_hook.py", line 55, in check_file
	    ast_obj = ast.parse(f.read(), filename=filename)
	  File "/usr/local/lib/python3.9/ast.py", line 50, in parse
	    return compile(source, filename, mode, flags,
	  File "apps/outreach/management/commands/job.py", line 69
	    match self.header_to_name.get(header):
	          ^
	SyntaxError: invalid syntax
```

Running `pre-commit clean` did not helped. And I'm using Python 3.10.2 environment.

**Comment by flaiming** [comment]
Neverming, it started working now somehow.
