### ISSUE TITLE
Error after upgrading from v4.1.0 to v4.2.0

### ISSUE THREAD

**Issue by starlightromero** [pre-commit/pre-commit-hooks#752]
When running the command `pre-commit install  --install-hooks --hook-type commit-msg --hook-type pre-commit --hook-type pre-push --overwrite` the following error occurs after upgrading to v4.2.0

### version information

```
pre-commit version: 2.10.0
sys.version:
    3.6.5 (default, Oct 20 2021, 11:18:56)
    [GCC Apple LLVM 13.0.0 (clang-1300.0.29.3)]
sys.executable: /Users/starlight.romero/.local/pipx/venvs/pre-commit/bin/python
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/starlight.romero/.cache/pre-commit/repowa0ybd2t/py_env-default/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /Users/starlight.romero/.cache/pre-commit/repowa0ybd2t
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'

stderr:
      ERROR: Command errored out with exit status 1:
       command: /Users/starlight.romero/.cache/pre-commit/repowa0ybd2t/py_env-default/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/starlight.romero/.cache/pre-commit/repowa0ybd2t/setup.py'"'"'; __file__='"'"'/Users/starlight.romero/.cache/pre-commit/repowa0ybd2t/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/th/yd1hbl_923n0yhfdnznypslc0000gp/T/pip-pip-egg-info-ibdb_stx
           cwd: /Users/starlight.romero/.cache/pre-commit/repowa0ybd2t/
      Complete output (6 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/Users/starlight.romero/.cache/pre-commit/repowa0ybd2t/setup.py", line 1
          from __future__ import annotations
          ^
      SyntaxError: future feature annotations is not defined
      ----------------------------------------
    WARNING: Discarding file:///Users/starlight.romero/.cache/pre-commit/repowa0ybd2t. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by asottile** [comment]
pre-commit-hooks 4.2.0 has dropped end-of-lifed python versions (<3.7): https://github.com/pre-commit/pre-commit-hooks/blob/main/CHANGELOG.md#420---2022-04-06

**Comment by starlightromero** [comment]
Here is my python version

```
python3 --version                                                                                                                                                                                                       
Python 3.9.12
```

**Comment by asottile** [comment]
the output above shows pre-commit 2.10.0 (pretty old) and python 3.6.5 -- perhaps you need to reinstall pre-commit to python 3.9.x?
