### ISSUE TITLE
check-added-large-files IndexError in filter_lfs_files

### ISSUE THREAD

**Issue by fdcavalcanti** [pre-commit/pre-commit-hooks#810]
Running the check-added-large-files is throwing the following error:
IndexError: list index out of range

```
More details:
Traceback (most recent call last):
  File "/home/fdcavalcanti/.cache/pre-commit/repouawq6m2z/py_env-python3/bin/check-added-large-files", line 8, in <module>
    sys.exit(main())
  File "/home/fdcavalcanti/.cache/pre-commit/repouawq6m2z/py_env-python3/lib/python3.8/site-packages/pre_commit_hooks/check_added_large_files.py", line 75, in main
    return find_large_added_files(
  File "/home/fdcavalcanti/.cache/pre-commit/repouawq6m2z/py_env-python3/lib/python3.8/site-packages/pre_commit_hooks/check_added_large_files.py", line 45, in find_large_added_files
    filter_lfs_files(filenames_filtered)
  File "/home/fdcavalcanti/.cache/pre-commit/repouawq6m2z/py_env-python3/lib/python3.8/site-packages/pre_commit_hooks/check_added_large_files.py", line 30, in filter_lfs_files
    filename, filter_tag = stdout[i], stdout[i + 2]
IndexError: list index out of range
```

Here's the data on stdout that is returned from the zsplit command. I replaced some names with 'nonononotests'.
`['nonononotests/tool/tests/temperature/test_temp_board.py: filter: unspecified\nnonononotests/tool2/support/files/logo/nonononotests.bin: filter: unspecified\ndocs/source/nonononotests.production.rst: filter: unspecified\nnonononotests/tool2/tests/dac/test_dac_scan.py: filter: unspecified\n']
`

CentOS 7
Linux -- 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Python 3.8.12

**Comment by asottile** [comment]
your version of git is 10 years old

**Comment by mikecuoco** [comment]
I'm having this same issue with pre-commit-hooks v4.5 and git 2.42.0

**Comment by asottile** [comment]
that is unlikely.  the error above is specifically due to very very old git output

**Comment by mikecuoco** [comment]
I have an old version of git on the HPC I work on, but I just installed 2.42.0 in my conda environment and retried the commit. Is there something else I should do to have pre-commit recognize the new version of git?

**Comment by asottile** [comment]
whatever is first on the PATH will get used.  nothing special

**Comment by mikecuoco** [comment]
yup, sorry. It was still using the older version, `which git` was giving an inaccurate result. Sorry again!
