### ISSUE TITLE
`tomli` is not a dependency for python<3.11

### ISSUE THREAD

**Issue by yajo** [pre-commit/pre-commit-hooks#833]
It is only an installation dependency, but not a runtime dependency:

https://github.com/pre-commit/pre-commit-hooks/blob/c03226380c96d030bc5988907f6fb638b58badfb/setup.cfg#L21-L23

I'm getting:

```
Traceback (most recent call last):
  File "/nix/store/06qpfmlgkhxakgjs8g7gk5jlkczij0m6-python3.10-pre-commit-hooks-4.3.0/bin/.check-toml-wrapped", line 6, in <module>
    from pre_commit_hooks.check_toml import main
  File "/nix/store/06qpfmlgkhxakgjs8g7gk5jlkczij0m6-python3.10-pre-commit-hooks-4.3.0/lib/python3.10/site-packages/pre_commit_hooks/check_toml.py", line 10, in <module>
    import tomli as tomllib
ModuleNotFoundError: No module named 'tomli'
```

**Comment by asottile** [comment]
install_requires is how runtime dependencies are specified

I suspect this is nix breaking in weird ways since they patch pre-commit in unsupported ways

**Comment by yajo** [comment]
Indeed, fixing in https://github.com/NixOS/nixpkgs/pull/200178. Thanks!
