### ISSUE TITLE
check-yaml: could not determine a constructor for the tag 'tag:yaml.org,2002:value'

### ISSUE THREAD

**Issue by aleksandr-vin** [pre-commit/pre-commit-hooks#846]
Having a _sample.yaml_:
```
op: =
```
pre-commit fails with:
```
check yaml...............................................................Failed
- hook id: check-yaml
- exit code: 1

could not determine a constructor for the tag 'tag:yaml.org,2002:value'
  in "sample.yaml", line 1, column 5
```

_.pre-commit-config.yaml_:
```
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
```

**Comment by asottile** [comment]
yeah you have invalid yaml try quoting the value

**Comment by aleksandr-vin** [comment]
Can you explain where it is invalid? I didn't find anything proving in the specs and also any validators complaining, for ex.:
```
$ cat <<EOF | yamllint -v -
op: =
EOF
yamllint 1.28.0
```

**Comment by aleksandr-vin** [comment]
To add a bit of context, I'm getting that yaml part in the process of converting a json data into yaml, with the pipeline like this:
```
echo '{"op":"="}' | jq . | yq -P eval
```
And the json I receive from Grafana's `/api/dashboards/uid/{uid}` api call. So it's not easy/tidy to _quote_ the value.

**Comment by asottile** [comment]
look I don't make the rules, it errors when loading:

```yaml
>>> import yaml
>>> yaml.load('op: =')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: load() missing 1 required positional argument: 'Loader'
>>> yaml.safe_load('op: =')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/asottile/opt/venv/lib/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/home/asottile/opt/venv/lib/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/home/asottile/opt/venv/lib/python3.10/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/home/asottile/opt/venv/lib/python3.10/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/asottile/opt/venv/lib/python3.10/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/home/asottile/opt/venv/lib/python3.10/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/home/asottile/opt/venv/lib/python3.10/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/asottile/opt/venv/lib/python3.10/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/home/asottile/opt/venv/lib/python3.10/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:value'
  in "<unicode string>", line 1, column 5:
    op: =
        ^
```
