### ISSUE TITLE
Cannot install pre-commit on M1

### ISSUE THREAD

**Issue by HendrikHuel** [pre-commit/pre-commit-hooks#868]
I am on a M1 with python 3.9. 

If I try to run `pre-commit`, I get the following error:

```
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/user/.cache/pre-commit/repo8y8cwuz_/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Processing /Users/user/.cache/pre-commit/repo8y8cwuz_
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [17 lines of output]
          Traceback (most recent call last):
            File "/Users/user/.cache/pre-commit/repo8y8cwuz_/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
              main()
            File "/Users/user/.cache/pre-commit/repo8y8cwuz_/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/Users/user/.cache/pre-commit/repo8y8cwuz_/py_env-python3/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/c7/bvg2x30n43vg_jf9md3xnmx80000gp/T/pip-build-env-au_b36g0/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/private/var/folders/c7/bvg2x30n43vg_jf9md3xnmx80000gp/T/pip-build-env-au_b36g0/overlay/lib/python3.11/site-packages/poetry/core/factory.py", line 57, in create_poetry
              raise RuntimeError("The Poetry configuration is invalid:\n" + message)
          RuntimeError: The Poetry configuration is invalid:
            - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
          
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /Users/user/.cache/pre-commit/pre-commit.log
```

My python environment via conda with a manual `pip` installed `isort==5.12.0` looks like:

```
# Name                    Version                   Build  Channel
ca-certificates           2023.01.10           hca03da5_0  
certifi                   2022.12.7        py39hca03da5_0  
cfgv                      3.3.1                    pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
filelock                  3.9.0                    pypi_0    pypi
identify                  2.5.17                   pypi_0    pypi
isort                     5.12.0                   pypi_0    pypi
libcxx                    14.0.6               h848a8c0_0  
libffi                    3.4.2                hca03da5_6  
ncurses                   6.4                  h313beb8_0  
nodeenv                   1.7.0                    pypi_0    pypi
openssl                   1.1.1s               h1a28f6b_0  
pip                       22.3.1           py39hca03da5_0  
platformdirs              2.6.2                    pypi_0    pypi
pre-commit                3.0.2                    pypi_0    pypi
python                    3.9.16               hc0d8a6c_0  
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h1a28f6b_0  
setuptools                65.6.3           py39hca03da5_0  
sqlite                    3.40.1               h7a7dc30_0  
tk                        8.6.12               hb8d0fd4_0  
tzdata                    2022g                h04d1e81_0  
virtualenv                20.17.1                  pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.10               h80987f9_1  
zlib                      1.2.13               h5a0b063_0
```

I already tried to run it with a cleared `.cache/pre-commit`, but it did not help.

**Comment by MarcoGorelli** [comment]
you just need to upgrade the isort version

**Comment by HendrikHuel** [comment]
> 

What do you mean? I installed isort 5.12.0 (newest version) in my environment.

**Comment by MarcoGorelli** [comment]
which version do you have in your .pre-commit-config.yaml file?

**Comment by HendrikHuel** [comment]
> which version do you have in your .pre-commit-config.yaml file?

My .yaml is the following
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ".dat"
      - id: trailing-whitespace
        exclude: ".dat"
      - id: debug-statements
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        stages: [commit, push]
        types: [python]
        exclude: ".dat"
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        language_version: python3
```
