### ISSUE TITLE
Pre-commit-hooks cannot find pip on arm macbook

### ISSUE THREAD

**Issue by apollocatlin** [pre-commit/pre-commit-hooks#879]
I am getting the following errors only with the pre-commit-hooks packages on an M2 Mac with homebrew, pyenv and python 3.11. I also tested this with system python 3.9 after uninstalling brew python, pyenv, and installing pre-commit with pip rather than brew.

This is my log output. I have all of my other hooks working on this but when I use these hooks i get the following error message. Any assistance would be lovely, and I am more than happy to test etc if anything else is needed. Cannot find any duplicate issues explaining these errors.

### version information

```
pre-commit version: 3.0.4
git --version: git version 2.39.2
sys.version:
    3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)]
sys.executable: /opt/homebrew/Cellar/pre-commit/3.0.4/libexec/bin/python3.11
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/apollo/.cache/pre-commit/repo6yt1a3nw/py_env-python3.11/bin/python', '-mpip', 'install', '.')
return code: 1
stdout: (none)
stderr:
    /Users/apollo/.cache/pre-commit/repo6yt1a3nw/py_env-python3.11/bin/python: No module named pip.__main__; 'pip' is a package and cannot be directly executed
    
```

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/pre-commit/3.0.4/libexec/lib/python3.11/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/homebrew/Cellar/pre-commit/3.0.4/libexec/lib/python3.11/site-packages/pre_commit/main.py", line 394, in main
    return run(args.config, store, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pre-commit/3.0.4/libexec/lib/python3.11/site-packages/pre_commit/commands/run.py", line 437, in run
    install_hook_envs(to_install, store)
  File "/opt/homebrew/Cellar/pre-commit/3.0.4/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 239, in install_hook_envs
    _hook_install(hook)
  File "/opt/homebrew/Cellar/pre-commit/3.0.4/libexec/lib/python3.11/site-packages/pre_commit/repository.py", line 86, in _hook_install
    lang.install_environment(
  File "/opt/homebrew/Cellar/pre-commit/3.0.4/libexec/lib/python3.11/site-packages/pre_commit/languages/python.py", line 214, in install_environment
    helpers.run_setup_cmd(prefix, install_cmd)
  File "/opt/homebrew/Cellar/pre-commit/3.0.4/libexec/lib/python3.11/site-packages/pre_commit/languages/helpers.py", line 49, in run_setup_cmd
    cmd_output_b(*cmd, cwd=prefix.prefix_dir, **kwargs)
  File "/opt/homebrew/Cellar/pre-commit/3.0.4/libexec/lib/python3.11/site-packages/pre_commit/util.py", line 115, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/apollo/.cache/pre-commit/repo6yt1a3nw/py_env-python3.11/bin/python', '-mpip', 'install', '.')
return code: 1
stdout: (none)
stderr:
    /Users/apollo/.cache/pre-commit/repo6yt1a3nw/py_env-python3.11/bin/python: No module named pip.__main__; 'pip' is a package and cannot be directly executed
```

**Comment by asottile** [comment]
please show your configuration, the command you ran, and its full output

**Comment by apollocatlin** [comment]
Config

```
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
   ```
   
   Command and output:
   ```
   pre-commit run -a
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/apollo/.cache/pre-commit/repo6yt1a3nw/py_env-python3.11/bin/python', '-mpip', 'install', '.')
return code: 1
stdout: (none)
stderr:
    /Users/apollo/.cache/pre-commit/repo6yt1a3nw/py_env-python3.11/bin/python: No module named pip.__main__; 'pip' is a package and cannot be directly executed

Check the log at /Users/apollo/.cache/pre-commit/pre-commit.log
```

**Comment by asottile** [comment]
what version of `virtualenv` do you have? perhaps its cache got poisoned through a bad `rm -rf` ?  it usually lives at '~/Library/Application\ Support/virtualenv/'

maybe try this command to temporarily move it out of the way?

```bash
mv ~/Library/Application\ Support/virtualenv{,.tmp}/
```

**Comment by asottile** [comment]
also does this give any output? `env | grep PYTHON | sort` ?

**Comment by apollocatlin** [comment]
`env | grep PYTHON | sort` does not give output.

`mv ~/Library/Application\ Support/virtualenv{,.tmp}/` worked! this is a restored system from backup. which likely caused.

Thank you!

**Comment by asottile** [comment]
maybe report to `virtualenv` then? idk it's not a pre-commit problem in that case

**Comment by apollocatlin** [comment]
Will do, thank you. It was only manifesting here, as I do not spend much time in python. But if anyone else runs into the issue this can be indexed. Thank you again!
